services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: eunice
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: flaskdb

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: flaskdb